### ISSUE TITLE
How to use option '-p'

### ISSUE THREAD

**Issue by GlLamant** [open-license-manager/lcc-license-generator#4]
I create a file named "private_key"(maybe i'm right ^~^), and push the md5 value of example into "private_key".Then I perform './license_generator example -o example.lic -p private_key'. I try any ways i can do, but private_key likes is unuse , i have modified this, or delete this .So, is there anyone who knows how to use option '-p'?

**Comment by gcontini** [comment]
options -p replaced by --private-key
