### ISSUE TITLE
compiling error in visual studio 2015

### ISSUE THREAD

**Issue by drjtan** [open-license-manager/lcc-license-generator#8]
Help please!
c:\github\lcc-license-generator\src\license_generator\../inja/inja.hpp(1971): error C2678: binary '!=': no operator found which takes a left-hand operand of type 'nonstd::sv_lite::string_view' (or there is no acceptable conversion)

**Comment by gcontini** [comment]
I'm very sorry the documentation was not updated. The support for visual studio 2015 has been abandoned. I'll fix the documentation in next days. Minimum version is Visual Studio 2017.
